
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${RESOURCE_NAME}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ${PARAMS.host}
      http:
        paths:
          - path: ${PARAMS.path}
            pathType: Prefix
            backend:
              service:
                name: ${SERVICE_NAME}
                port:
                  number: ${PARAMS.port}
